affiliate/product/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('affiliate.product.views',
	url(r'^api/$', 'product_api', name="product-api"),
	url(r'^(?P<slug>[a-z0-9-]+)/$', 'product_detail', name='product-detail'),
	url(r'^(?P<id>[0-9]+)/resurface/$', 'resurface_product', name='product-resurface'),
)

affiliate/tag/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('affiliate.tag.views',
	url(r'^(?P<slug>[a-z0-9-]+)/$', 'tagged_product_list', name='tagged-product-list'),
)

affiliate/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

handler404 = 'affiliate.views.custom_404'
handler500 = 'affiliate.views.custom_500'

urlpatterns = patterns('',
    url(r'^$', 'affiliate.views.home', name='home'),
    url(r'^p/', include('affiliate.product.urls')),
    url(r'^t/', include('affiliate.tag.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^sitemap.xml$', 'affiliate.views.sitemap', name='sitemap'),
)

affiliate/product/models.py
from random import shuffle

from django.core.urlresolvers import reverse
from django.db import models


def _get_standard_upload_folder(instance, filename):
	return u"{}/standard/{}".format(instance.site.domain, filename)

def _get_promo_upload_folder(instance, filename):
	return u"{}/promo/{}".format(instance.site.domain, filename)

class Product(models.Model):

	THEME_CHOICES = (
		('light', 'Light'),
		('dark', 'Dark'),
	)

	title = models.TextField()
	slug = models.SlugField(max_length=128, blank=True)

	external_url = models.URLField()
	product_ref = models.CharField(max_length=255, unique=True)

	description = models.TextField()
	price = models.DecimalField(decimal_places=2, max_digits=7)
	currency = models.ForeignKey('product.Currency')

	is_promo = models.BooleanField(default=False)
	partner_site = models.ForeignKey('site.AffiliateSite')
	site = models.ForeignKey('site.Site', related_name="products")

	added_date = models.DateTimeField(auto_now_add=True)

	image = models.ImageField(upload_to=_get_standard_upload_folder, blank=True, null=True)
	promo_image = models.ImageField(upload_to=_get_promo_upload_folder, blank=True, null=True)
	theme = models.CharField(max_length=15, choices=THEME_CHOICES, default='light')

	tags = models.ManyToManyField('tag.Tag', blank=True, null=True)

	class Meta:
		ordering = ['-added_date']
		unique_together = ("site", "slug")

	def __unicode__(self):
		return u"{}: {}".format(self.product_ref, self.title)

	def get_relative_url(self):
		return reverse('product-detail', kwargs={"slug": self.slug})

	def get_absolute_url(self):
		return u"http://{domain}{path}".format(domain=self.site.domain, path=self.get_relative_url())

	def similar_products(self, count=4):
		products = list(Product.objects.filter(site_id=self.site_id).exclude(id=self.id))
		shuffle(products)
		return products[:count]


class Currency(models.Model):
	iso_4217 = models.CharField(max_length=5)
	symbol = models.CharField(max_length=5)

	def __unicode__(self):
		return u"{}: {}".format(self.iso_4217, self.symbol)

affiliate/site/models.py
from django.db import models


class Site(models.Model):
	name = models.CharField(max_length=255, unique=True)
	domain = models.CharField(max_length=255, db_index=True)

	meta_title = models.TextField(blank=True)
	meta_description = models.TextField(blank=True)

	story = models.TextField(blank=True)

	tracking_code = models.CharField(max_length=128, blank=True)

	def __unicode__(self):
		return unicode(self.name)


class AffiliateSite(models.Model):
	name = models.CharField(max_length=255)
	domain = models.CharField(max_length=255)
	affiliate_tracking_code = models.TextField()

	def __unicode__(self):
		return unicode(self.name)

affiliate/tag/models.py
from django.core.urlresolvers import reverse
from django.db import models


class Tag(models.Model):

	title = models.CharField(max_length=128)
	slug = models.SlugField(max_length=128)
	description = models.TextField()
	site = models.ForeignKey('site.Site', related_name="tags")
	
	def __unicode__(self):
		return unicode(self.title)

	def get_relative_url(self):
		return reverse('tagged-product-list', kwargs={"slug": self.slug})

	def get_absolute_url(self):
		return u"http://{domain}{path}".format(domain=self.site.domain, path=self.get_relative_url())

affiliate/product/views.py
import datetime

from django import http
from django.conf import settings
from django.contrib.auth.decorators import permission_required
from django.shortcuts import render

from affiliate.utils.shortcuts import redirect_back

from .models import Product


def product_detail(request, slug):

	try:
		product = Product.objects.select_related('currency', 'partner_site').get(site=request.site, slug=slug)
	except Product.DoesNotExist:
		raise http.Http404

	# saves an SQL lookup when rendering product.get_absolute_url
	product.site = request.site

	context = {
		'product': product,
		'tags': product.tags.all(),
		'similar_products': product.similar_products(count=4),
	}

	return render(request, "detail.html", context)


def product_api(request):
	try:
		page_num = int(request.GET['page'])
	except (ValueError, KeyError):
		return http.HttpResponseBadRequest()

	page_size = settings.PRODUCT_API_PAGE_SIZE
	offset = (page_num - 1) * page_size

	products = Product.objects.filter(site=request.site)[offset:offset+page_size]

	if not products:
		return http.HttpResponseBadRequest()

	return render(request, 'snippets/product_grid.html', {"products": products});


@permission_required('product.change_product')
def resurface_product(request, id):

	try:
		product = Product.objects.get(id=id)
	except Product.DoesNotExist:
		raise http.Http404

	product.added_date = datetime.datetime.now()
	product.save()

	return redirect_back(request)

affiliate/tag/views.py
from django.shortcuts import render

from .models import Tag

# Create your views here.

def tagged_product_list(request, slug):

	try:
		tag = Tag.objects.get(site=request.site, slug=slug)
	except Tag.DoesNotExist:
		raise http.Http404

	context = {
		'tag': tag,
	}

	return render(request, "tagged_product_list.html", context)

affiliate/views.py
import random

from django.conf import settings
from django.shortcuts import render


def home(request):
	products = request.site.products.select_related('currency')
	promos = products.filter(is_promo=True)

	context = {
		"products": products[:settings.PRODUCT_API_PAGE_SIZE],
		"promos": promos[:3],
	}

	return render(request, "home.html", context)


def sitemap(request):
	products = request.site.products.all()
	tags = request.site.tags.all()

	context = {
		"products": products,
		"tags": tags,
	}
	return render(request, "sitemap.xml", context, content_type="application/xhtml+xml")


def custom_404(request):
	count = request.site.products.count()
	random_num = random.choice(range(1, count))
	random_product = request.site.products.all()[random_num - 1]
	return render(request, '404.html', {"product": random_product}, status=404)


def custom_500(request):
	count = request.site.products.count()
	random_num = random.choice(range(1, count))
	return render(request, '500.html', status=500)

templates/base.html
{% load staticfiles %}

<html>
	<head>
		{% block meta %}
		<meta charset="UTF-8">
        <meta name="google-site-verification" content="47mrkhgjyVNoPKfjh_ci2o3WsX9FlOOzNpWkfgguME8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
		<meta name="description" content="{{ request.site.meta_description }}">
		<title>{{ request.site.meta_title }}</title>
		{% endblock %}
		<link href='//fonts.googleapis.com/css?family=Open+Sans:800' rel='stylesheet' type='text/css'>
		<link href='//fonts.googleapis.com/css?family=Merriweather' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" type="text/css" href="{% static 'css/site.css' %}">
	</head>
	<body>
		{% block header %}
		<header id="site-header">
			<h1><a href="/">{{ request.site.name }}</a></h1>
			<div class="social">
				<a href="https://twitter.com/intent/user/?screen_name=verymanlythings" class="button twitter follow"><i></i>@verymanlythings</a>
			</div>
		</header>
		{% endblock %}
		<div id="content-wrapper">
			{% block content %}{% endblock %}
			<div id="content-push"></div>
		</div>
		{% block footer %}
		<footer>
			<div class="small">
				&copy; {% now "Y" %} {{ request.site.name }}
			</div>
		</footer>
		{% endblock %}
		{% block scripts %}
		<script type="text/javascript" src="{% static 'js/main.js' %}"></script>
		<script>
			{% if debug %}/* -- commented for debug --{% endif %}
			(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
			(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
			m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
			})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

			ga('create', '{{ request.site.tracking_code }}', 'auto');
			ga('send', 'pageview');
			{% if debug %}-- commented for debug -- */{% endif %}
		</script>
		{% endblock %}
	</body>
</html>

templates/detail.html
{% extends 'base.html' %}
{% load markdown_tags %}

{% block meta %}
	{{ block.super }}
	<meta name="twitter:card" content="summary_large_image">
	<meta name="twitter:site" content="@verymanlythings">
	<meta name="twitter:title" content="{{ product.title }}">
	<meta name="twitter:description" content="{{ product.description|summary }}">
	<meta name="twitter:image:src" content="http://{{ request.site.domain }}{{ product.image.url }}">
{% endblock %}

{% block content %}
	<main id="product-detail">
		<section class="product clearfix">
			<figure>
				<img src="{{ product.image.url }}">
			</figure>
			<div class="details">
				<h1>{{ product.title }}</h1>
				<div class="price">from {{ product.currency.symbol}}{{ product.price }}</div>
				<a href="{{ product.external_url }}" class="button partner-link">View on {{ product.partner_site }}</a>
				<hr />
				{% if tags %}
				{% for tag in tags %}
					{% if not forloop.first %}
						• 
					{% endif %}
					<a href="{{ tag.get_relative_url }}" class="tag">{{ tag }}</a>
				{% endfor %}
				<hr />
				{% endif %}
				<a href="https://twitter.com/intent/tweet?url={{ product.get_absolute_url|urlencode }}&via=verymanlythings" class="button twitter tweet"><i></i>Tweet</a>
			</div>
		</section>

		<section class="description">
			{{ product.description|markdown }}
		</section>


		<section class="similar-products clearfix">
			<h3>You might also like...</h3>

			{% for similar in similar_products %}
			<figure class="similar-product">
				<a href="{{ similar.get_relative_url }}"><img src="{{ similar.image.url }}"></a>
				<figcaption>
					<h4><a href="{{ similar.get_relative_url }}">{{ similar.title }}</a></h4>
				</figcaption>
			</figure>
			{% endfor %}
		</section>
	</main>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load markdown_tags %}

{% block content %}
	<main id="homepage">
		{% for promo in promos %}
		<section class="promo-slide" style="background-image: url('{{ promo.promo_image.url }}');">
			<div class="info clearfix {{ promo.theme }}">
				<h2>{{ promo.title }}</h2>
				<div class="details">
					<span class="price">{{ promo.currency.symbol }}{{ promo.price }}</span>
					<a href="{{ promo.get_relative_url }}">View details</a>
				</div>
			</div>
			{% if forloop.first %}
				<div class="scrollDown {{ promo.theme }}">
				    Scroll Down
				    <svg height="20" width="200">
				        <path d="M100 15 L200 0 L100 10 L0 0 Z" />
				    </svg>
				</div>
			{% endif %}
		</section>
		{% endfor %}
		<section class="site-story">
			<h1>{{ request.site.name }}</h1>
			{{ request.site.story|markdown }}
		</section>
		<div class="product-list clearfix" id="product-grid">
			{% include 'snippets/product_grid.html' %}
		</div>
		<div id="scrollLoader">
			<div class="bounce1"></div>
			<div class="bounce2"></div>
			<div class="bounce3"></div>
		</div>
	</main>
{% endblock %}

{% block scripts %}
{{ block.super }}
<script type="text/javascript">
	Components.infiniteScroll('/p/api/', function(res) {
		var node = document.getElementById('product-grid');
		node.insertAdjacentHTML('beforeend', res.responseText);
	});
</script>
{% endblock %}

templates/snippets/product_grid.html
{% for product in products %}
<figure class="product">
	<img src="{{ product.image.url }}" alt="{{ product.title }}">
	<figcaption>
		<h2>{{ product.title }}</h2>
		<a href="{{ product.get_relative_url }}">View details</a>
	</figcaption>
</figure>
{% endfor %}

templates/tagged_product_list.html
{% extends 'base.html' %}
{% load markdown_tags %}

{% block content %}
	<main id="tagged-products">
		<section class="intro">
			<h1>{{ tag.title }}</h1>
			{{ tag.description|markdown}}
		</section>

		<section class="products clearfix">
			{% for product in tag.product_set.all %}
			<figure class="product">
				<a href="{{ product.get_relative_url }}"><img src="{{ product.image.url }}"></a>
				<figcaption>
					<h4><a href="{{ product.get_relative_url }}">{{ product.title }}</a></h4>
				</figcaption>
			</figure>
			{% endfor %}
		</section>
	</main>
{% endblock %}